name: Docker Build and push image.
on:
    push:
        branches: master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.3
              with:
                  token: ${{ github.token }}
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Docker Login
              uses: docker/login-action@v1.6.0
              with:
                  username: ${{ secrets.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
                  logout: false
            - name: Docker Build
              id: docker_build
              uses: docker/build-push-action@v2.0.1
              with:
                  labels: binaryapi
                  push: true
                  tags: ${{ secrets.DOCKERHUB_ORG }}/${{ secrets.DOCKERHUB_REPO }}:latest
            - name: Image Digest
              run: echo ${{ steps.docker_build.outputs.digest }}
